### PR TITLE
Fixes issue with `and` assertion not being applied correctly. Fixes #176

### LINKED ISSUE #176: [bug] Chained assertions after `.and` doesn't seem to work
It seems like the usage of `.and` prevents assertions that follow it from failing the whole test. For example:

```kotlin
expectThat("one")
    .and {
        isEqualTo("one")
    }
    .isEqualTo("two")
```

Clearly, this test should fail, because of the last `.isEqualTo("two")`, but in fact it succeeds. Failed assertions inside the `.and` will fail the whole test, but not anything after the block.

### PR DESCRIPTION
**Pull request by cjbrooks12**
I believe this is the root cause for #176. The `and` assertion was returning `AssertionBuilder(nestedContext, Collecting)` from the `.let { }` block, which meant that any assertions downstream from that `.and` call were being collected instead of thrown.

By returning a separate builder with the original context (which is `Throwing` at the top-level`) things seem to be working again.

### CODE REVIEW

File: strikt-core/src/main/kotlin/strikt/internal/AssertionBuilder.kt [hunk 1]
```diff
@@ -32,11 +32,14 @@ internal class AssertionBuilder<T>(
...
     AssertionChainedGroup(context, context.subject)
       .let { nestedContext ->
+        // collect assertions from a child block
         AssertionBuilder(nestedContext, Collecting)
           .apply(assertions)
           .also {
             strategy.evaluate(nestedContext)
           }
+        // return the original context and AssertionStrategy for chaining
+        AssertionBuilder(context, strategy)
```
Comment (robfletcher) [inline strikt-core/src/main/kotlin/strikt/internal/AssertionBuilder.kt]: Could it return `this`?

**Comment by robfletcher** [comment]
Nice, good spot.

File: strikt-core/src/main/kotlin/strikt/internal/AssertionBuilder.kt (hunk 1 above)
Comment (cjbrooks12) [reply strikt-core/src/main/kotlin/strikt/internal/AssertionBuilder.kt]: Fixed
